### ISSUE TITLE
less中使用if函数结果异常

### ISSUE THREAD

**Issue by berwin0415** [ecomfe/reskript#292]
在less文件中使用if函数进行条件判断，最后结果异常
代码
```less
.max (@bool) {
    width: if(@bool, 520px, 100%);
}

.box {
    .max(true);

    .inner {
        .max(false);
    }
}
```
```tsx
      <div className={styles.box}>
          <div className={styles.inner}>test</div>
      </div>
```

结果：
<img width="1237" alt="image" src="https://user-images.githubusercontent.com/36828535/172521925-419455a2-a8d9-4e54-90ae-c89b230e9ce2.png">
<img width="1346" alt="image" src="https://user-images.githubusercontent.com/36828535/172521951-7b5309a2-e5e5-42bf-8240-52bf2758e5bd.png">
