### ISSUE TITLE
给默认的HTML模板加一个dir属性

### ISSUE THREAD

**Issue by otakustay** [ecomfe/reskript#299]
通过`postcss-preset-env`编译后，`margin-inline-start`会编译成`margin-left/right`并配合`dir="ltr | rtl"`来起作用，没有`dir`属性就会出事

例如`div { margin-inline-start: 10px; }`编译后大概长这样：

```css
[dir="ltr"] div {
    margin-left: 10px;
}

[dir="rtl"] div {
    margin-right: 10px;
}
```

所以默认的模板，在`<body>`上加一个`dir="ltr"`，自定义模板自己想办法
